//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class err_01
    {
        public int a01 { get; set; }
        public Nullable<System.DateTime> a02 { get; set; }
        public Nullable<System.DateTime> a03 { get; set; }
        public string a04 { get; set; }
        public string a05 { get; set; }
        public string a06 { get; set; }
        public string a07 { get; set; }
        public string a08 { get; set; }
        public string a09 { get; set; }
        public string a10 { get; set; }
    }
}
