//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class M_CORDERC
    {
        public string CCODE { get; set; }
        public int IORDER { get; set; }
        public string CMTEID { get; set; }
        public string CCMTEID { get; set; }
        public string CCOLORID { get; set; }
        public string CWHID { get; set; }
        public string CDESC { get; set; }
        public decimal DQTY { get; set; }
        public decimal DPRICE { get; set; }
        public byte INETFLAG { get; set; }
        public decimal DDEQTY { get; set; }
        public Nullable<decimal> DCOST { get; set; }
        public Nullable<decimal> DCYPRICE { get; set; }
        public Nullable<decimal> DCYCOST { get; set; }
        public decimal DAGIOC { get; set; }
        public Nullable<decimal> dshipqty { get; set; }
        public string cpocode { get; set; }
        public Nullable<int> cpoorder { get; set; }
        public string cattrid { get; set; }
        public Nullable<decimal> dprice2 { get; set; }
        public string csalman { get; set; }
        public Nullable<decimal> dprise { get; set; }
        public string cplanflag { get; set; }
        public string ctaxflag { get; set; }
        public string cindentflag { get; set; }
        public Nullable<System.DateTime> ddedt { get; set; }
        public Nullable<decimal> dpayqty { get; set; }
        public string cstateflag { get; set; }
        public string creadyflag { get; set; }
        public Nullable<decimal> dunpackamt { get; set; }
        public Nullable<decimal> drate { get; set; }
        public string cagioempid { get; set; }
        public string cpomanid { get; set; }
        public Nullable<decimal> damtc { get; set; }
        public Nullable<decimal> dreamtc { get; set; }
        public string cstation1 { get; set; }
        public string counterid { get; set; }
        public string crejtype { get; set; }
        public string cpoflag { get; set; }
        public string cpostate { get; set; }
        public Nullable<decimal> dpercent { get; set; }
        public string cpodesc { get; set; }
        public string clargessflag { get; set; }
        public Nullable<decimal> drejqty { get; set; }
        public string cunitid { get; set; }
        public string cpcode { get; set; }
        public Nullable<int> iporder { get; set; }
        public string BargainFlag { get; set; }
        public Nullable<decimal> dshipplanqty { get; set; }
        public Nullable<decimal> dpack_qty { get; set; }
        public Nullable<decimal> dpoqty { get; set; }
        public Nullable<decimal> dvinqty { get; set; }
        public Nullable<decimal> dTranprice { get; set; }
        public string cquotid { get; set; }
        public Nullable<int> iquotorder { get; set; }
        public string csetflag { get; set; }
        public Nullable<System.DateTime> dshipdate { get; set; }
        public Nullable<decimal> dnotaxprice { get; set; }
        public Nullable<decimal> dpriseprice { get; set; }
        public string cvipflag { get; set; }
        public Nullable<decimal> dplanqty { get; set; }
        public string ctype { get; set; }
    
        public virtual M_CORDER M_CORDER { get; set; }
    }
}
