//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class M_POLIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_POLIST()
        {
            this.M_POLISTC = new HashSet<M_POLISTC>();
        }
    
        public string CCODE { get; set; }
        public string CTYPE { get; set; }
        public string CFLAG { get; set; }
        public string BEGINMAN { get; set; }
        public Nullable<System.DateTime> BEGINDT { get; set; }
        public string EDITMAN { get; set; }
        public Nullable<System.DateTime> EDITDT { get; set; }
        public string CMTMAN { get; set; }
        public Nullable<System.DateTime> CMTDT { get; set; }
        public byte INETFLAG { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[JsonIgnore]//添加特性标签  
        public virtual ICollection<M_POLISTC> M_POLISTC { get; set; }
    }
}
