//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class M_StoreChange
    {
        public string db { get; set; }
        public string ccode { get; set; }
        public int iorder { get; set; }
        public string cmteid { get; set; }
        public int changeFlag { get; set; }
        public decimal quantity { get; set; }
        public System.DateTime changeDate { get; set; }
        public string repertory { get; set; }
        public string backup1 { get; set; }
        public string backup2 { get; set; }
        public string backup3 { get; set; }
    }
}
