//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class M_STOCK
    {
        public string CMTEID { get; set; }
        public string CMTEID_text { get; set; }
        public string CWHID { get; set; }
        public string CWHID_text { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string Backup1 { get; set; }
        public string Backup2 { get; set; }
        public string Backup3 { get; set; }
    }
}
