//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class mao_file
    {
        public string mao01 { get; set; }
        public string mao02 { get; set; }
        public string mao03 { get; set; }
        public string mao04 { get; set; }
        public string mao05 { get; set; }
        public string mao06 { get; set; }
        public string mao07 { get; set; }
        public string mao08 { get; set; }
        public string maoacti { get; set; }
    }
}
