//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class map_file
    {
        public string map01 { get; set; }
        public string map02 { get; set; }
        public string map03 { get; set; }
        public string map04 { get; set; }
        public string map05 { get; set; }
        public string map06 { get; set; }
        public string map07 { get; set; }
        public string map08 { get; set; }
        public string mapacti { get; set; }
    }
}
