//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_accountinfo
    {
        public int iorder { get; set; }
        public string ccode { get; set; }
        public string cname { get; set; }
        public string cstyle { get; set; }
        public string cstatus { get; set; }
        public string cdbname { get; set; }
        public string ccomputer { get; set; }
        public string cdbuser { get; set; }
        public string cdbpwd { get; set; }
        public string csupper { get; set; }
        public string csuppwd { get; set; }
        public string cupgrade { get; set; }
    }
}
