//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_colorset
    {
        public string db { get; set; }
        public string dbname { get; set; }
        public string CCOLORID { get; set; }
        public string CNAME { get; set; }
        public string CENAME { get; set; }
        public Nullable<int> iorder { get; set; }
        public string cbarcode { get; set; }
        public string ccolorstop { get; set; }
        public string cclassid { get; set; }
    }
}
