//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_corder
    {
        public string db { get; set; }
        public string CCODE { get; set; }
        public string CCUSTID { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string CCYID { get; set; }
        public string CPYID { get; set; }
        public decimal DAGIO { get; set; }
        public decimal DPAYAMT { get; set; }
        public decimal DPAYAMT1 { get; set; }
        public decimal DPAYAMT2 { get; set; }
        public System.DateTime DDEDT { get; set; }
        public string CDEADR { get; set; }
        public string CTRANS { get; set; }
        public string CCMAN { get; set; }
        public string CSALEMAN { get; set; }
        public string CREMARK { get; set; }
        public string CMTFLAG { get; set; }
        public string ENDFLAG { get; set; }
        public string BEGINMAN { get; set; }
        public Nullable<System.DateTime> BEGINDT { get; set; }
        public string EDITMAN { get; set; }
        public Nullable<System.DateTime> EDITDT { get; set; }
        public string CMTMAN { get; set; }
        public Nullable<System.DateTime> CMTDT { get; set; }
        public string ENDMAN { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public byte INETFLAG { get; set; }
        public decimal DAMT { get; set; }
        public decimal DCYAMT { get; set; }
        public string custphone { get; set; }
        public Nullable<decimal> dtaxrate { get; set; }
        public Nullable<decimal> dtaxamt { get; set; }
        public Nullable<decimal> drate { get; set; }
        public string ccontractno { get; set; }
        public string cchangeflag { get; set; }
        public string creadyflag { get; set; }
        public string cagioempid { get; set; }
        public string CORDER_CHANGEID { get; set; }
        public string ccancelflag { get; set; }
        public string cwhid { get; set; }
        public string cpyway { get; set; }
        public string cregionid { get; set; }
        public string cisship { get; set; }
        public string cpathid { get; set; }
        public string cischdedt { get; set; }
        public Nullable<System.DateTime> ddedt_new { get; set; }
        public Nullable<int> ipri { get; set; }
        public string ccounterid { get; set; }
        public string cstation1 { get; set; }
        public string cchremark { get; set; }
        public string cstockflag { get; set; }
        public string cforcestockflag { get; set; }
        public string cpostate { get; set; }
        public Nullable<decimal> DFREIGHTAMT { get; set; }
        public Nullable<int> cfreeflag1 { get; set; }
        public string cfreeflag2 { get; set; }
        public string cfreeflag3 { get; set; }
        public Nullable<int> iprint { get; set; }
        public string cfromcode { get; set; }
        public Nullable<decimal> dpayamt_old { get; set; }
        public Nullable<decimal> dpayamt1_old { get; set; }
        public Nullable<decimal> dagio_old { get; set; }
        public Nullable<decimal> damt_old { get; set; }
        public Nullable<byte> ifromnetflag { get; set; }
        public string cupdflag { get; set; }
        public string cbldflag { get; set; }
        public string cexflag { get; set; }
        public string ctenantflag { get; set; }
        public string ccinflag { get; set; }
        public string ccurplancode { get; set; }
        public string cautopoflag { get; set; }
        public Nullable<decimal> tally_damt { get; set; }
        public string cvipid { get; set; }
        public string cprivilegeid { get; set; }
        public string cannulmtman { get; set; }
        public Nullable<System.DateTime> cannulmtdt { get; set; }
        public string cmtdeamtflag { get; set; }
        public Nullable<System.DateTime> agiodt { get; set; }
        public Nullable<decimal> dcess { get; set; }
        public string csmsflg { get; set; }
        public string csmsman { get; set; }
        public Nullable<System.DateTime> csmsdt { get; set; }
        public string cstylist { get; set; }
        public Nullable<decimal> dcardamt { get; set; }
        public Nullable<decimal> dchargeamt { get; set; }
        public string cdeareaid { get; set; }
        public string cmtdeamtman { get; set; }
        public Nullable<System.DateTime> cmtdeamtdt { get; set; }
        public Nullable<decimal> dconsumamt { get; set; }
        public string crefereeman { get; set; }
        public string csignstylistid { get; set; }
        public string ccancelman { get; set; }
        public Nullable<System.DateTime> ccanceldt { get; set; }
        public string cappflag { get; set; }
        public string cappman { get; set; }
        public Nullable<System.DateTime> cappdt { get; set; }
        public string cprintman { get; set; }
        public Nullable<decimal> dpreamt { get; set; }
        public string email { get; set; }
        public string cpyid_text { get; set; }
        public string csaleman_text { get; set; }
        public string cwhid_text { get; set; }
        public string cpyway_text { get; set; }
    }
}
