//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_customer
    {
        public string db { get; set; }
        public string dbname { get; set; }
        public string CCUSTID { get; set; }
        public string CNAME { get; set; }
        public string CCNAME { get; set; }
        public string CENAME { get; set; }
        public string CADR1 { get; set; }
        public string CADR2 { get; set; }
        public string CDEADR1 { get; set; }
        public string CDEADR2 { get; set; }
        public string CINADR { get; set; }
        public string CCLASSID { get; set; }
        public string CBANK { get; set; }
        public string CBANKNO { get; set; }
        public string CMAIL { get; set; }
        public string CCONMAN { get; set; }
        public string CTEL { get; set; }
        public string CFAX { get; set; }
        public string EMAIL { get; set; }
        public string CWEB { get; set; }
        public string CCYID { get; set; }
        public string CPYID { get; set; }
        public string CADMIN { get; set; }
        public string CSALEMAN { get; set; }
        public string CSTATUS { get; set; }
        public Nullable<decimal> DCREDIT { get; set; }
        public Nullable<decimal> DAMT4 { get; set; }
        public Nullable<decimal> DAMT3 { get; set; }
        public Nullable<System.DateTime> DDATE1 { get; set; }
        public Nullable<decimal> DAMT1 { get; set; }
        public Nullable<System.DateTime> DDATE2 { get; set; }
        public Nullable<decimal> DAMT2 { get; set; }
        public string CREMARK { get; set; }
        public string BEGINMAN { get; set; }
        public Nullable<System.DateTime> BEGINDT { get; set; }
        public string EDITMAN { get; set; }
        public Nullable<System.DateTime> EDITDT { get; set; }
        public string cyusou { get; set; }
        public string cyinsou { get; set; }
        public string cyusoudf { get; set; }
        public Nullable<decimal> bzj { get; set; }
        public Nullable<decimal> yjbzj { get; set; }
        public string cconmante { get; set; }
        public string cdistflag { get; set; }
        public string cregionid { get; set; }
        public string csettlemodeid { get; set; }
        public string credit { get; set; }
        public string cvip { get; set; }
        public Nullable<int> resp_day { get; set; }
        public string cpivotflag { get; set; }
        public string cstation1 { get; set; }
        public Nullable<decimal> dagio_a { get; set; }
        public Nullable<int> cashflowidys { get; set; }
        public Nullable<int> cashflowids { get; set; }
        public Nullable<System.DateTime> dbirth { get; set; }
        public string careflag { get; set; }
        public string cresidential { get; set; }
        public string capartments { get; set; }
        public Nullable<decimal> darea { get; set; }
        public string cfurniture_style { get; set; }
        public string Cbrand { get; set; }
        public string csex { get; set; }
        public string cjob { get; set; }
        public string cfond { get; set; }
        public string coldlive { get; set; }
        public string cpet { get; set; }
        public string czxjd { get; set; }
        public Nullable<System.DateTime> dmarrydate { get; set; }
        public Nullable<System.DateTime> checkindate { get; set; }
        public string cstylist { get; set; }
        public string cdesign_company { get; set; }
        public Nullable<decimal> dhousesamt { get; set; }
        public string ccompetition_brand { get; set; }
        public string cqqnumber { get; set; }
        public string cworkunit { get; set; }
        public string csalary { get; set; }
        public string crelation { get; set; }
        public string CTRANS { get; set; }
        public string cdeareaid { get; set; }
        public string cpost { get; set; }
        public string cclassid_text { get; set; }
    }
}
