//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_prodcolor
    {
        public string db { get; set; }
        public string dbname { get; set; }
        public string CMTEID { get; set; }
        public string CCOLORID { get; set; }
        public decimal DCOST { get; set; }
        public decimal DPRICE2 { get; set; }
        public string CFROMADR { get; set; }
        public string CWHPLACE { get; set; }
        public string CLEVEL { get; set; }
        public string CDESC { get; set; }
        public Nullable<decimal> DPERCENT { get; set; }
        public Nullable<decimal> DPRISE { get; set; }
        public Nullable<decimal> DPRICE1 { get; set; }
        public string CATTRID { get; set; }
        public Nullable<decimal> DMINQTY { get; set; }
        public Nullable<decimal> DMAXQTY { get; set; }
        public Nullable<decimal> dprice_neap { get; set; }
        public Nullable<decimal> dpricea1 { get; set; }
        public Nullable<decimal> dpriceb1 { get; set; }
        public Nullable<decimal> dpricec1 { get; set; }
        public Nullable<decimal> dpriced1 { get; set; }
        public Nullable<decimal> dpricee1 { get; set; }
        public Nullable<decimal> dpricef1 { get; set; }
        public Nullable<decimal> pressprice { get; set; }
        public string crefcode { get; set; }
        public Nullable<int> iporder { get; set; }
        public string defultflag { get; set; }
        public string cname { get; set; }
    }
}
