//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_product1
    {
        public string db { get; set; }
        public string CMTEID { get; set; }
        public string CCNAME { get; set; }
        public string CSPEC { get; set; }
        public string CENAME { get; set; }
        public string CESPEC { get; set; }
        public string CUNITID { get; set; }
        public string CNAME { get; set; }
        public string CCLASSID { get; set; }
        public string CNAME_b { get; set; }
        public decimal DCOST { get; set; }
        public decimal DPRICE { get; set; }
        public Nullable<decimal> DWEIGHT { get; set; }
        public string CWTUNIT { get; set; }
        public Nullable<decimal> DVOLUME { get; set; }
        public string DVOLUNIT { get; set; }
        public string CVENDID { get; set; }
        public string vendor_name { get; set; }
        public string CLEVEL { get; set; }
        public Nullable<decimal> dpack_qty { get; set; }
        public string cunitname { get; set; }
        public string cattrid { get; set; }
        public string ccremark { get; set; }
        public string ceremark { get; set; }
        public string cattname { get; set; }
        public string caddress { get; set; }
        public string cstuff { get; set; }
        public string ccolorname { get; set; }
        public string CCOLORID { get; set; }
    }
}
