//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_product
    {
        public string db { get; set; }
        public string dbname { get; set; }
        public string CMTEID { get; set; }
        public string CCNAME { get; set; }
        public string CENAME { get; set; }
        public string CSPEC { get; set; }
        public string CESPEC { get; set; }
        public string CUNITID { get; set; }
        public string CCLASSID { get; set; }
        public decimal DCOST { get; set; }
        public decimal DPRICE2 { get; set; }
        public decimal DPRICE { get; set; }
        public string CVENDID { get; set; }
        public string CPRICETY { get; set; }
        public string CPHOTO { get; set; }
        public Nullable<decimal> DMAX { get; set; }
        public Nullable<decimal> DMIN { get; set; }
        public string DWHAREA { get; set; }
        public string DWHPLACE { get; set; }
        public Nullable<decimal> DWEIGHT { get; set; }
        public string CWTUNIT { get; set; }
        public Nullable<decimal> DVOLUME { get; set; }
        public string DVOLUNIT { get; set; }
        public string CFLAG2 { get; set; }
        public Nullable<short> ICYC { get; set; }
        public string CCREMARK { get; set; }
        public string CEREMARK { get; set; }
        public Nullable<System.DateTime> DSTARTDT { get; set; }
        public Nullable<System.DateTime> DSTOPDT { get; set; }
        public string CCUSTOM1 { get; set; }
        public string CUSTOME2 { get; set; }
        public string BEGINMAN { get; set; }
        public Nullable<System.DateTime> BEGINDT { get; set; }
        public string EDITMAN { get; set; }
        public Nullable<System.DateTime> EDITDT { get; set; }
        public string cacctno { get; set; }
        public string ccenben { get; set; }
        public string ccaigou { get; set; }
        public string cxiaosou { get; set; }
        public string csouru { get; set; }
        public string cxsfy { get; set; }
        public string cstop { get; set; }
        public string cattrid { get; set; }
        public Nullable<decimal> dlength { get; set; }
        public Nullable<decimal> dwidth { get; set; }
        public Nullable<decimal> dheight { get; set; }
        public string cdefwhid { get; set; }
        public string ckctj { get; set; }
        public string CPOMANID { get; set; }
        public string cbarcode { get; set; }
        public string cpackid { get; set; }
        public Nullable<int> iadvance { get; set; }
        public Nullable<int> iadvance_sea { get; set; }
        public Nullable<int> iadvance_other { get; set; }
        public string cabccode { get; set; }
        public string ccolorflag { get; set; }
        public Nullable<decimal> dpriceA { get; set; }
        public Nullable<decimal> dpriceB { get; set; }
        public Nullable<decimal> dpriceC { get; set; }
        public Nullable<decimal> dpriceD { get; set; }
        public Nullable<decimal> dpriceE { get; set; }
        public Nullable<decimal> dpriceF { get; set; }
        public Nullable<decimal> dprice_tiptop { get; set; }
        public Nullable<decimal> dprice_neap { get; set; }
        public string csetflag { get; set; }
        public Nullable<decimal> dagio { get; set; }
        public string cassflag { get; set; }
        public string cclassid2 { get; set; }
        public Nullable<decimal> dprise { get; set; }
        public Nullable<decimal> dpercent { get; set; }
        public string cisdagio { get; set; }
        public Nullable<decimal> pressprice { get; set; }
        public string cbrandid { get; set; }
        public string caddress { get; set; }
        public Nullable<decimal> dpack_qty { get; set; }
        public Nullable<int> itransport { get; set; }
        public Nullable<int> itransport_sea { get; set; }
        public Nullable<int> itransport_other { get; set; }
        public string csplit { get; set; }
        public string cpricenocolflag { get; set; }
        public string cphotoxgt { get; set; }
        public string cphotozzt { get; set; }
        public string cphotojt { get; set; }
        public Nullable<decimal> dnetweight { get; set; }
        public string cstuff { get; set; }
        public string cdetaildesc1 { get; set; }
        public string cdetaildesc2 { get; set; }
        public Nullable<decimal> dfreight { get; set; }
        public Nullable<decimal> dsetamt { get; set; }
        public Nullable<decimal> darea { get; set; }
    }
}
