//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_vendor
    {
        public string db { get; set; }
        public string CVENDID { get; set; }
        public string CNAME { get; set; }
        public string CCNAME { get; set; }
        public string CCLASSID { get; set; }
        public string CNAME_a { get; set; }
        public string CADR1 { get; set; }
        public string CMAIL { get; set; }
        public string CCONMAN { get; set; }
        public string CBANK { get; set; }
        public string CBANKNO { get; set; }
        public string CPYID { get; set; }
        public string CSTATUS { get; set; }
        public string CFLAG { get; set; }
        public string CPOMAN { get; set; }
        public string CLEVEL { get; set; }
        public string CCYID { get; set; }
        public string CTEL { get; set; }
        public Nullable<int> iadvance { get; set; }
        public Nullable<int> iadvance_sea { get; set; }
        public Nullable<int> iadvance_other { get; set; }
        public Nullable<int> ipocyc { get; set; }
        public Nullable<int> istcyc { get; set; }
        public string cycid { get; set; }
        public string cacctvendid { get; set; }
        public string cpomanname { get; set; }
        public Nullable<decimal> dtaxrate { get; set; }
        public string csettlemodeid { get; set; }
        public string FStlName { get; set; }
    }
}
