//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_vorderc
    {
        public string CCODE { get; set; }
        public int IORDER { get; set; }
        public string CMTEID { get; set; }
        public string CVMTEID { get; set; }
        public string CCOLORID { get; set; }
        public string CWHID { get; set; }
        public string CDESC { get; set; }
        public decimal DQTY { get; set; }
        public decimal DPRICE { get; set; }
        public byte INETFLAG { get; set; }
        public Nullable<decimal> DDEQTY { get; set; }
        public string CPPLANID { get; set; }
        public Nullable<int> IPORDER { get; set; }
        public Nullable<decimal> DCYPRICE { get; set; }
        public Nullable<decimal> DCYCOST { get; set; }
        public decimal DAGIOC { get; set; }
        public string CPOMANID { get; set; }
        public string corid { get; set; }
        public Nullable<int> icorder { get; set; }
        public string cpodesc { get; set; }
        public Nullable<decimal> dtaxprice { get; set; }
        public Nullable<decimal> dpack_qty { get; set; }
        public Nullable<System.DateTime> plango_date { get; set; }
        public Nullable<System.DateTime> factgo_date { get; set; }
        public Nullable<System.DateTime> ddedtc { get; set; }
        public string cattrid { get; set; }
        public string cvcolorid { get; set; }
        public Nullable<decimal> dstandardcost { get; set; }
        public string cmteid_text { get; set; }
        public string ccolorid_text { get; set; }
        public string cattrid_text { get; set; }
        public string cwhid_text { get; set; }
        public string cmteid_unit { get; set; }
        public string db { get; set; }
    }
}
