//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_vorder
    {
        public string db { get; set; }
        public string CCODE { get; set; }
        public string CVENDID { get; set; }
        public Nullable<System.DateTime> DDATE { get; set; }
        public string CMAN { get; set; }
        public string CACCPMAN { get; set; }
        public string CTRANS { get; set; }
        public System.DateTime DDEDT { get; set; }
        public string CDEADR { get; set; }
        public string CPYID { get; set; }
        public string CCYID { get; set; }
        public decimal DAGIO { get; set; }
        public decimal DPAYAMT { get; set; }
        public decimal DPAYAMT1 { get; set; }
        public string CREMARK { get; set; }
        public string CMTFLAG { get; set; }
        public string ENDFLAG { get; set; }
        public string BEGINMAN { get; set; }
        public Nullable<System.DateTime> BEGINDT { get; set; }
        public string EDITMAN { get; set; }
        public Nullable<System.DateTime> EDITDT { get; set; }
        public string CMTMAN { get; set; }
        public Nullable<System.DateTime> CMTDT { get; set; }
        public string ENDMAN { get; set; }
        public Nullable<System.DateTime> ENDDT { get; set; }
        public byte INETFLAG { get; set; }
        public decimal DAMT { get; set; }
        public decimal DCYAMT { get; set; }
        public string cpyway { get; set; }
        public Nullable<decimal> drate { get; set; }
        public string cvendphone { get; set; }
        public string cpoflag { get; set; }
        public string cacct_vendid { get; set; }
        public Nullable<decimal> dtaxrate { get; set; }
        public Nullable<decimal> DFREIGHTAMT { get; set; }
        public string cbldflag { get; set; }
        public string cexflag { get; set; }
        public Nullable<System.DateTime> plango_date { get; set; }
        public Nullable<System.DateTime> factgo_date { get; set; }
        public string cannulmtman { get; set; }
        public Nullable<System.DateTime> cannulmtdt { get; set; }
        public string cdecode { get; set; }
        public string ctransportid { get; set; }
        public decimal dtransportamt { get; set; }
        public Nullable<int> iprint { get; set; }
        public string cprintman { get; set; }
        public string CVENDID_text { get; set; }
        public string CCYID_text { get; set; }
        public string cpyway_text { get; set; }
        public string CPYID_text { get; set; }
        public string CMTFLAG_text { get; set; }
    }
}
