//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupBuy1.Models
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public partial class v_warehous1
    {
        public string db { get; set; }
        public string CWHID { get; set; }
        public string CREMARK { get; set; }
        public string CADR { get; set; }
        public string CTEL { get; set; }
        public string CNAME { get; set; }
        public string CADMIN { get; set; }
        public byte INETFLAG { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public string csalesflag { get; set; }
        public string ccalcflag { get; set; }
        public string isstation { get; set; }
        public string cstation { get; set; }
        public string cshopid { get; set; }
        public string cshopman { get; set; }
        public string CCLASSID { get; set; }
        public string cclassname { get; set; }
        public string CLEVEL { get; set; }
    }
}
